zkp2p/zk-p2p

circuits/configs/test4_email_verify.config
circuits/configs/test_ex4_email_verify.config
circuits/src/lib.rs
circuits/test_data/test4_email_body_defs.json
circuits/test_data/test4_send_amount_defs.json
circuits/test_data/test_ex4_email_body_defs.json

TODO: Only default regex, circuit still not written

Venmo send email regex

---

circuits-circom/test/venmo_receive.js
circuits-circom/venmo_receive.circom

TODO
- Need new solidity verifier and calldata

Use zkemail template to verify RSA

---

circuits-circom/regex_to_circom/regex_to_dfa.js
circuits-circom/scripts/upload_to_s3.py

- Fix script for s3 upload
- Fix regex generation script

Fix upload to s3 script

---

circuits-circom/contracts/VenmoRegistrationVerifier.sol

Calldata
```
["0x2cff8a69249a6296247ec0b54c62db9e53e7708e6cf770dd552a196bf9911d5a", "0x0ccf1fe6ba4f18b843bf5ed3b5d29813eedfca2bfc4dd9bf4094144e5201f2d4"],[["0x206c18d0ea140756e12395ab36706f488224aac98f9acf58f929ffd499aa4b34", "0x22ab61193d731a53f47fcaec0bd9d4b5f3b21af77c749a59754450f8543ba393"],["0x1ca5527010d293f079be50554e6dea9c327ac942497a5add65dbda1d568f41f9", "0x163fa370d71e14b1b58fe902bce5bacf4b3c28c69bc16700198eee897e7b00d2"]],["0x2fe4d1f6ef5f37516f4b4349b750c8d15ffe90b6efaa270aefa0c2ad3dd24a90", "0x25252599e588d9197d1bdf1650a31d81c4c2edb2ea4aa27092c6a2e0494d16c1"],["0x0000000000000000000000000000000000000000000000000076406f6d6e6576","0x000000000000000000000000000000000000000000000000006f632e6f6d6e65","0x000000000000000000000000000000000000000000000000000000000000006d","0x0000000000 …
```

Add Venmo Registration Verifier

---

client/src/components/RegistrationForm/ExistingRegistration.tsx
client/src/helpers/abi/fusdc.abi.ts
client/src/helpers/abi/ramp.abi.ts
client/src/helpers/deployed_addresses.ts
client/src/index.js
contracts/README.md

- Update ABIs for ramp contract and fUSDC
- Add new deployed address configuration for hardhat
- Updated chain config to include Hardhat
- Update README for getting started with hardhat local node

Add Hardhat Configuratioj

---

client/src/App.tsx
client/src/components/Deposit/OffRamperProof.tsx
client/src/components/RegistrationForm/NewRegistrationProof.tsx
client/src/components/Swap/OnRamperProof.tsx
client/src/contexts/ProofGenSettings/ProofGenSettingsContext.ts
client/src/contexts/ProofGenSettings/ProofGenSettingsProvider.tsx
client/src/contexts/ProofGenSettings/index.ts
client/src/hooks/useLocalStorage.ts

Added first instance of shared app context

Add ProofGenSettings Context

---

client/src/App.tsx
client/src/components/Deposit/OffRamperProof.tsx
client/src/components/Deposit/OffRamperSubmit.tsx
client/src/components/RegistrationForm/ExistingRegistration.tsx
client/src/components/RegistrationForm/NewRegistration.tsx
client/src/components/RegistrationForm/NewRegistrationSubmit.tsx
client/src/components/Swap/OnRamperProof.tsx
client/src/components/Swap/OnRamperSubmit.tsx
client/src/components/common/ConnectButton.tsx
client/src/components/layouts/TopNav/index.tsx
client/src/contexts/Account/AccountContext.ts
client/src/contexts/Account/AccountProvider.tsx
client/src/contexts/RampRegistration/RampRegistrationContext.ts
client/src/contexts/RampRegistration/RampRegistrationProvider.tsx
client/src/contexts/RampRegistration/index.ts
client/src/contexts/RampRegistration/types.ts
client/src/helpers/abi/ramp.abi.ts
client/src/hooks/useAccount.ts
client/src/hooks/useRampRegistration.ts

* Update ramp abi from new contract
* Add registration context for fetching a logged in user's registration status
* Return ramp contract addresses with account context

Wire New Ramp Contract

---

circuits-circom/.npmignore
circuits-circom/README.md
circuits-circom/package.json
circuits-circom/scripts/generate_input.ts
circuits-circom/yarn.lock

Published `@zkp2p/circuits-circom 0.0.1`

Publish `zkp2p/circuits-circom` package with new gen input script

---

client/package.json
client/src/App.tsx
client/src/contexts/Balances/BalancesContext.ts
client/src/contexts/Balances/BalancesProvider.tsx
client/src/contexts/Balances/index.ts
client/src/contexts/Balances/types.ts
client/src/helpers/bignumber.ts
client/src/hooks/useBalance.ts
client/yarn.lock

* Add new context, provider, and hook for fetching eth and usdc balances
* Also added context for fetching usdc's approval to ramp contract

Add Balances and Approval Context

---

client/config/webpack.config.js
client/src/components/Deposit/NewPosition.tsx
client/src/components/RegistrationForm/SubmitRegistration.tsx
client/src/components/common/SingleLineInput.tsx
client/src/contexts/Balances/BalancesProvider.tsx
client/src/contexts/RampRegistration/RampRegistrationContext.ts
client/src/contexts/RampRegistration/RampRegistrationProvider.tsx
client/src/helpers/units.ts

- Add new balance context and provider to fetch necessary balances and approvals
- Update NewPosition component with convenience fee input
- Update SingleLineInput field to have error string
- Add error string helpers to guide user if approvals / balances are insufficient to deposit
- Add helpers to translate on chain usdc and wei units to human readable values

Wire New Position Flow

---

client/src/components/Deposit/NewPosition.tsx
client/src/components/Deposit/PositionTable.tsx
client/src/components/Deposit/index.tsx
client/src/components/layouts/TopNav/NavItem.tsx
client/src/components/layouts/TopNav/index.tsx
client/src/contexts/Account/AccountContext.ts
client/src/contexts/Account/AccountProvider.tsx
client/src/contexts/Balances/BalancesProvider.tsx
client/src/contexts/RampRegistration/RampRegistrationProvider.tsx

Ignore branch name. Took a detour to build in navigation fix and allow Deposit page to navigate to Registration if user is not properly registered on chain. Taking another detour to fix existing context and providers before completing wiring of Deposit page table.

Fix Navigation with useLocation

---

client/src/components/Deposit/NewPosition.tsx
client/src/components/Deposit/OffRamperIntentRow.tsx
client/src/components/Deposit/OffRamperIntentTable.tsx
client/src/components/Deposit/PositionTable.tsx
client/src/components/Deposit/index.tsx
client/src/contexts/Balances/BalancesProvider.tsx
client/src/contexts/Deposits/DepositsProvider.tsx
client/src/contexts/Ramp/RampProvider.tsx

- Update table rows for deposits and off ramper intents
- Update Position and OffRamperIntent tables to properly update as state is retreived

Update Deposit and OffRamper Display

---

circuits-circom/package.json
circuits-circom/scripts/generate_input.ts

Add support for nonce. Nonce allows us to handle multiple emails during hosted proving generation.

Fix gen input script

---

client/src/App.tsx
client/src/components/Deposit/NewPosition.tsx
client/src/components/Deposit/PositionTable.tsx
client/src/components/PermissionsForm/NewPermission.tsx
client/src/components/PermissionsForm/PermissionTable.tsx
client/src/components/common/ProofGenerationForm.tsx
client/src/contexts/Permissions/PermissionsContext.ts
client/src/contexts/Permissions/PermissionsProvider.tsx
client/src/contexts/Permissions/index.ts
client/src/hooks/usePermissions.ts

Add smart contract txn call to NewPermission component.

Add Submit New Permission

---

client/src/App.tsx
client/src/components/Deposit/NewPosition.tsx
client/src/components/Deposit/PositionTable.tsx
client/src/components/PermissionsForm/NewPermission.tsx
client/src/components/PermissionsForm/PermissionTable.tsx
client/src/components/common/ProofGenerationForm.tsx
client/src/contexts/Permissions/PermissionsContext.ts
client/src/contexts/Permissions/PermissionsProvider.tsx
client/src/contexts/Permissions/index.ts
client/src/hooks/usePermissions.ts

Utilize permissions hook and populate permissions table.

Wire Permissions

---

client/package.json
client/src/components/Deposit/NewPosition.tsx
client/src/components/PermissionsForm/PermissionTable.tsx
client/src/components/Swap/OnRamperIntentTable.tsx
client/src/components/Swap/index.tsx
client/src/contexts/Account/AccountContext.ts
client/src/contexts/Account/AccountProvider.tsx
client/src/contexts/Balances/BalancesContext.ts
client/src/contexts/Balances/BalancesProvider.tsx
client/src/contexts/Balances/types.ts
client/src/contexts/Deposits/DepositsContext.ts
client/src/contexts/Deposits/DepositsProvider.tsx
client/src/contexts/Liquidity/LiquidityContext.ts
client/src/contexts/Liquidity/LiquidityProvider.tsx
client/src/contexts/Liquidity/helper.ts
client/src/contexts/OnRamperIntents/OnRamperIntentsContext.ts
client/src/contexts/OnRamperIntents/OnRamperIntentsProvider.tsx
client/src/contexts/Permissions/PermissionsContext.ts
client/src/contexts/Permissions/PermissionsProvider.tsx
client/src/contexts/Ramp/RampProvider.tsx
client/src/contexts/Registration/RegistrationContext.ts
client/src/contexts/Registration/RegistrationProvider.tsx
client/src/helpers/constants.ts
client/yarn.lock

* Integrate 0.0.7 circuits
* Clean up providers and contexts, all uninitialized state begins as null for more consistency instead of empty strings, zero addresses, and empty arrays
* Update app to use keep any contract state in bigints

Integrate 0.0.7 Circuits

---

client/src/components/Deposit/OffRamperIntentRow.tsx
client/src/components/Deposit/OffRamperIntentTable.tsx
client/src/components/Swap/OnRamperIntentRow.tsx
client/src/components/Swap/OnRamperIntentTable.tsx
client/src/contexts/Deposits/types.ts
client/src/contexts/Liquidity/LiquidityProvider.tsx
client/src/contexts/OnRamperIntents/OnRamperIntentsContext.ts
client/src/contexts/OnRamperIntents/OnRamperIntentsProvider.tsx
client/src/helpers/constants.ts

* Added new OnRampIntent type to track Intents along with depositor venmo id
* Updated intent tables and rows for on and off rampers to convey meaningful information about the order

Update Intent Rows

---

client/src/App.tsx
client/src/components/Deposit/NewPosition.tsx
client/src/components/Deposit/SubmitOffRamp.tsx
client/src/components/PermissionsForm/NewPermission.tsx
client/src/components/RegistrationForm/SubmitRegistration.tsx
client/src/components/Swap/SubmitOnRamp.tsx
client/src/components/Swap/index.tsx

* Utilize enabled flag on write config setup to only build transaction if the parameters are configured correctly

Clean Up Contract Write Configs

---

client/src/components/Deposit/NewPosition.tsx
client/src/components/Deposit/OffRamperIntentRow.tsx
client/src/components/Deposit/OffRamperIntentTable.tsx
client/src/components/Deposit/PositionRow.tsx
client/src/components/Deposit/PositionTable.tsx
client/src/components/Deposit/index.tsx
client/src/components/Swap/OnRamperIntentRow.tsx
client/src/components/Swap/OnRamperIntentTable.tsx
client/src/components/Swap/index.tsx
client/src/contexts/Deposits/DepositsProvider.tsx
client/src/contexts/Deposits/types.ts
client/src/contexts/Liquidity/LiquidityContext.ts
client/src/contexts/Liquidity/LiquidityProvider.tsx
client/src/contexts/Liquidity/helper.ts
client/src/helpers/constants.ts
client/src/helpers/units.ts

* Properly calculate conversion rate to show on off ramper deposit table
* Add helper to calculate usd amount to send from requested USDC and conversion rate
* Display calculated usd amount to send in swap modal input, on ramper order intent, and off ramper order

Support Fractional Inputs

---

client/config/webpack.config.js
client/package.json
client/src/components/Button.tsx
client/src/components/Deposit/OffRamp.tsx
client/src/components/ProofGen/ProofForm.tsx
client/src/components/ProofGen/ProvingWorker.tsx
client/src/components/RegistrationForm/NewRegistration.tsx
client/src/components/Swap/Input.tsx
client/src/components/Swap/OnRamp.tsx
client/src/components/Swap/index.tsx
client/src/components/modals/Modal.tsx
client/tsconfig.json
client/yarn.lock

- Move client side proof gen off of main thread to not freeze UI
- Add accessory label to input to show USDC balance on swap modal
- Add loading state to proof gen modal when submitting and mining a proof

Add Web Worker

---

client/src/components/Deposit/OffRamperIntentTable.tsx
client/src/components/Deposit/PositionTable.tsx
client/src/components/ProofGen/ProofForm.tsx
client/src/components/Swap/OnRamperIntentTable.tsx
client/src/components/modals/Modal.tsx
client/src/components/modals/VerificationStepRow.tsx
client/src/helpers/tooltips.ts

Saving generated proofs for emails to local storage

Caching Generated Proofs

---

client/src/components/Deposit/NewPosition.tsx
client/src/components/ProofGen/ProofForm.tsx
client/src/components/RegistrationForm/NewRegistration.tsx
client/src/contexts/ProofGenSettings/ProofGenSettingsProvider.tsx
client/src/contexts/Registration/RegistrationContext.ts
client/src/contexts/Registration/RegistrationProvider.tsx

- Locally cache venmo id when use successfully registers
- Load cached venmo ID into new deposit form

Cache Venmo ID Locally

---

client/src/components/Deposit/OffRamp.tsx
client/src/components/ProofGen/ProofForm.tsx
client/src/components/ProofGen/types.tsx
client/src/components/RegistrationForm/NewRegistration.tsx
client/src/components/Swap/OnRamp.tsx
client/src/components/modals/Modal.tsx
client/src/components/modals/VerificationStepRow.tsx
client/src/helpers/tooltips.ts

- Adding step to proof gen modal to indicate status of the transaction

Add Submit Step to Proof Modal

---

circuits-circom/build/venmo_receive/venmo_receive_js/generate_witness.js
circuits-circom/build/venmo_receive/venmo_receive_js/witness_calculator.js
circuits-circom/build/venmo_registration/venmo_registration_js/generate_witness.js
circuits-circom/build/venmo_registration/venmo_registration_js/witness_calculator.js
circuits-circom/build/venmo_send/venmo_send_js/generate_witness.js
circuits-circom/build/venmo_send/venmo_send_js/witness_calculator.js
circuits-circom/scripts/generate_input.ts

- Add build files for each circuit

Add build files

---

circuits-circom/regexes/venmo_actor_id.circom
circuits-circom/test/venmo_registration.spec.ts
circuits-circom/venmo_registration.circom

Fix registration regex

---

client/package.json
client/src/App.tsx
client/src/components/Button.tsx
client/src/components/Deposit/OffRamp.tsx
client/src/components/Deposit/OffRamperIntentRow.tsx
client/src/components/Deposit/PositionTable.tsx
client/src/components/ProofGen/MailRow.tsx
client/src/components/ProofGen/MailTable.tsx
client/src/components/ProofGen/ProofForm.tsx
client/src/components/ProofGen/ProofSettings.tsx
client/src/components/ProofGen/UploadEmail.tsx
client/src/components/RegistrationForm/NewRegistration.tsx
client/src/components/Swap/OnRamp.tsx
client/src/components/Swap/OnRamperIntentRow.tsx
client/src/components/Swap/PaymentModal.tsx
client/src/components/common/AccessoryButton.tsx
client/src/components/common/NumberedStep.tsx
client/src/contexts/GoogleAuth/GoogleAuthContext.ts
client/src/contexts/GoogleAuth/GoogleAuthProvider.tsx
client/src/contexts/GoogleAuth/index.ts
client/src/contexts/GoogleAuth/types.ts
client/src/contexts/ProofGenSettings/ProofGenSettingsContext.ts
client/src/contexts/ProofGenSettings/ProofGenSettingsProvider.tsx
client/src/helpers/tooltips.ts
client/src/hooks/useGmailClient.ts
client/src/hooks/useGoogleAuth.ts
client/yarn.lock

I did too many cool things here to list them all. Ping me to demo if you're following along

Google Auth and Simple QR Flow

---

circuits-circom/regexes/venmo_payee_id.circom
circuits-circom/regexes/venmo_payee_id.json
circuits-circom/scripts/generate_input.ts
circuits-circom/test/regexes/venmo_payee_id.spec.ts
circuits-circom/test/venmo_send.spec.ts
circuits-circom/venmo_registration.circom
circuits-circom/venmo_send.circom

For circuit updates, please provide a brief description of the changes included in this PR.
- Extract onramper ID in the same payee regex
- Breaking change to smart contract and UI. Additional public output and new private input for gen input script
For any circuit changes, complete the following steps to ensure faster integration with UI and Smart Contracts:
Send circuit calldata
["0x2a1eba4b96b534094d82a3b5624bb750af53aae2d21b90fbbe239d145b8983fd", "0x12e8698eac09b6b7861a168099242a8b3044c6b7720b4f453101a274bbdb2b94"],[["0x25a5073001984435c489b3318e07b93d1755a763889a734fb8cd2f6bb713006a", "0x1561b6ebd796ecc5b52cc6e6f7226f5c0a20e952cc4d1dcd0b3a3e23e116cf23"],["0x2400aa61e06f1b046d184a33e44132ef2d3995f533e4967396cf9e59a5569747", "0x10f9d78505a387a15ad9b7bef2c5df65d349f31f2c396a6710dd4dfa1d8 …

v0.0.10 Extract onramper ID

---

client/package.json
client/src/components/Swap/index.tsx
client/src/contexts/OnRamperIntents/OnRamperIntentsContext.ts
client/src/contexts/OnRamperIntents/OnRamperIntentsProvider.tsx
client/src/contexts/Ramp/RampContext.ts
client/src/contexts/Ramp/RampProvider.tsx
client/src/helpers/abi/ramp.abi.ts
client/src/helpers/abi/send.abi.ts
client/src/helpers/constants.ts
client/src/helpers/deployed_addresses.ts
client/yarn.lock
contracts/deploy/deploy_contracts.ts
contracts/utils/constants.ts

- Retrieve onRampCooldownPeriod as part of Ramp context
- Retrieve getLastOnRampTimestamp as part of OnRamperIntents context
- Configure Swap to check if on ramp cooldown period has elapsed

Update to 0.0.10

---

client/src/components/RegistrationForm/ExistingRegistration.tsx

Update registration button name

---

client/src/components/ProofGen/MailTable.tsx

- Add detailed privacy and safety docs
- https://zkp2p.gitbook.io/zkp2p/user-guides/on-ramping/privacy-and-safety
- Update link

Update link to privacy and safety docs

---

client/src/App.tsx
client/src/components/Deposit/OffRamperIntentTable.tsx
client/src/components/Deposit/PositionRow.tsx
client/src/components/Deposit/PositionTable.tsx
client/src/components/Deposit/index.tsx
client/src/components/ProofGen/MailTable.tsx
client/src/components/ProofGen/ProofForm.tsx
client/src/components/ProofGen/ProofSettings.tsx
client/src/components/Swap/OnRamperIntentTable.tsx
client/src/components/common/AccessoryButton.tsx
client/src/components/common/Spinner.tsx
client/src/components/common/TextButton.tsx
client/src/components/layouts/TopNav/NavItem.tsx
client/src/components/modals/Modal.tsx
client/src/components/modals/VerificationStepRow.tsx
client/src/contexts/Deposits/DepositsProvider.tsx
client/src/contexts/GoogleAuth/GoogleAuthProvider.tsx
client/src/pages/Deposit.tsx
client/src/pages/Permissions.tsx
client/src/pages/Registration.tsx
client/src/pages/Swap.tsx

- Fixing warnings for a clear console
- Update AccessoryButton color set for primary and secondary buttons
- Wire Withdraw and Cancel Intent loading state correctly

Address Warnings

---

client/src/components/modals/VerificationStepRow.tsx
client/src/helpers/tooltips.ts

Updates timer to 30 seconds now that @0xSachinK has improved the validation times

Update timing of validation

---

client/src/components/ProofGen/ProofSettings.tsx
client/src/components/modals/Modal.tsx
client/src/components/modals/VerificationStepRow.tsx
client/src/helpers/tooltips.ts
client/src/index.js
client/src/pages/Registration.tsx

Update Proving Progress Circle

---

client/src/components/ProofGen/MailTable.tsx
client/src/helpers/strings/hdfc.ts

- Fixed instruction strings
- Fixed bug in parsing recipient UPI IDs from emails

Update HDFC instructions

---

circuits-circom/scripts/generate_input.ts
circuits-circom/scripts/preprocess_input.ts
circuits-circom/test/preprocess_input.spec.ts

Fix HDFC preprocess email

---

circuits-circom/.yarnrc.yml
circuits-circom/contracts/venmo_send_verifier.sol

Uploaded to `v2.5/0.1.2`
Venmo Send
["0x17a69a8eba69c1425769806a045097d50cea165cf38396d00e9a09fb80e0d4f4", "0x1f6a633eee86d31bc4f97b35dee45a2bd73ccfec5e90b095792992ca965c9045"],[["0x2ea34b13c37dcbcc970e86da3e9e553f335f8472e8c2bdb1232a0bfa58fd8509", "0x21c6a6c9a160f7580f2f45c191550813720874352e4578bd578679d9ed0ba932"],["0x09e5caa4d002b9d3c9b8f5b56939b063846ef99ca7e7d43f8e97f39ff474e84d", "0x25d3280e92842cd082004cc9350cdf0cff7e78f290213c4670f4b9d34eef5b4e"]],["0x29be16f2b99997c75f4e190299debac46ac6403d10b446e318d6188884d3ce65", "0x1a8754df60c01389e0be6787c121d167e85daaaf98385ff8b7bcd36974b9bad3"],["0x2cf6a95f35c0d2b6160f07626e9737449a53d173d65d1683263892555b448d8f","0x0000000000000000000000000000000000000000000000000076406f6d6e6576","0x000000000000000000000000000000000000000000000000006f632e …

Update venmo send keys + cpp binary

---

client/src/components/Deposit/Input.tsx
client/src/components/Deposit/hdfc/NewPosition.tsx
client/src/components/Swap/SwapModal.tsx
client/src/helpers/docUrls.ts
client/src/helpers/strings/hdfc.ts

Add HDFC minor UI updates

---

client/src/components/Account/AccountDropdown.tsx
client/src/contexts/common/Account/AccountContext.ts
client/src/contexts/common/Account/AccountProvider.tsx

Update login and account dropdown

---

client/src/components/Send/index.tsx
client/src/contexts/common/Balances/BalancesContext.ts
client/src/contexts/common/Balances/BalancesProvider.tsx
client/src/contexts/common/SmartContracts/SmartContractsContext.ts
client/src/contexts/common/SmartContracts/SmartContractsProvider.tsx
client/src/helpers/constants.ts
client/src/helpers/deployed_addresses.ts
client/src/hooks/useLifiBridge.ts

Add Lifi Logic

---

client/src/components/Deposit/wise/NewAccountRegistration.tsx
client/src/components/Deposit/wise/NewPosition.tsx
client/src/components/Notary/NotarizationTable.tsx
client/src/components/Notary/VerificationStepRow.tsx
client/src/components/Registration/wise/ExistingRegistration.tsx
client/src/components/Swap/SwapModal.tsx
client/src/contexts/common/ExtensionNotarizations/ExtensionNotarizationsProvider.tsx
client/src/helpers/docUrls.ts
client/src/helpers/strings/platform.ts
client/src/helpers/strings/wise.ts
client/src/pages/Landing.tsx

- Add EUR to the landing page carousel
- Update trouble scanning QR code link to direct to pay via desktop
- Update wise descriptions and tooltips
- Update "Add to Chrome" URL to link to Chrome extension
- Update links to relevant pages in docs

Update wise descriptions and tooltips

---

client/src/components/Notary/NotarizationTable.tsx
client/src/contexts/common/ExtensionNotarizations/ExtensionNotarizationsContext.ts
client/src/contexts/common/ExtensionNotarizations/ExtensionNotarizationsProvider.tsx
client/src/hooks/useBrowserExtension.ts

Open Sidebar CTA automatically opens Registration or On-Ramp

Add Messages to Navigate to Correct Action

---

client/src/components/Notary/NotarizationTable.tsx

https://linear.app/zkp2p/issue/ZKP-47/[notarizationtable]-filter-transfer-notary-proofs

Filter notarizations after intent timestamp

---

client/src/components/Swap/index.tsx
client/src/contexts/common/SwapQuote/SwapQuoteContext.ts
client/src/contexts/common/SwapQuote/SwapQuoteProvider.tsx
client/src/contexts/garanti/Liquidity/LiquidityProvider.tsx
client/src/contexts/garanti/Ramp/RampContext.ts
client/src/contexts/garanti/Ramp/RampProvider.tsx
client/src/contexts/hdfc/Liquidity/LiquidityProvider.tsx
client/src/contexts/hdfc/Ramp/RampContext.ts
client/src/contexts/hdfc/Ramp/RampProvider.tsx
client/src/contexts/revolut/Liquidity/LiquidityProvider.tsx
client/src/contexts/revolut/Ramp/RampContext.ts
client/src/contexts/revolut/Ramp/RampProvider.tsx
client/src/contexts/venmo/Liquidity/LiquidityProvider.tsx
client/src/contexts/venmo/Ramp/RampContext.ts
client/src/contexts/venmo/Ramp/RampProvider.tsx
client/src/helpers/constants.ts

Adding dynamic max on ramp button.

---

client/src/components/Notary/NotarizationTable.tsx
client/src/contexts/common/SwapQuote/SwapQuoteProvider.tsx
client/src/contexts/garanti/Liquidity/LiquidityProvider.tsx
client/src/contexts/hdfc/Liquidity/LiquidityProvider.tsx
client/src/contexts/revolut/Liquidity/LiquidityProvider.tsx
client/src/contexts/venmo/Liquidity/LiquidityProvider.tsx
client/src/helpers/strings/common.ts

Add Browser Check, Require Sidebar Support

---

client/src/App.tsx
client/src/components/Account/AccountDropdown.tsx
client/src/components/layouts/BottomNav/index.tsx
client/src/components/layouts/MenuDropdown/index.tsx
client/src/components/layouts/TopNav/index.tsx
client/src/hooks/useMediaQuery.ts
client/src/pages/Deposit.tsx
client/src/pages/Landing.tsx
client/src/pages/Liquidity.tsx
client/src/pages/Privacy.tsx
client/src/pages/Registration.tsx
client/src/pages/Send.tsx
client/src/pages/Swap.tsx
client/src/pages/Tos.tsx
client/src/pages/Withdraw.tsx

Create BottomBar for Mobile Experience

---

client/src/components/Registration/ReadOnlyInput.tsx
client/src/components/modals/PlatformIconHelper.tsx
client/src/components/modals/PlatformRow.tsx
client/src/helpers/strings/common.ts

Add PlatformIconHelper to PlatformRow

---

circuits-circom/circuits/namecheap/namecheap_push.circom
circuits-circom/circuits/namecheap/test/namecheap_push.spec.ts
circuits-circom/package/generate_input.ts
circuits-circom/scripts/upload_to_s3.py

TBD - additional hashing to prevent rainbow attacks

Namecheap review fixes

---

circuits-circom/circuits/namecheap/contracts/namecheap_push_verifier.sol
circuits-circom/circuits/namecheap/package.json
circuits-circom/package/package.json
circuits-circom/scripts/5_gen_proof.sh
circuits-circom/scripts/upload_to_s3.py

Calldata
```["0x1faa1f88e5fd6d2f29721aa11f1e4eb1f7d56f6e841968e612e6fd97036c8d21", "0x1703084da3ec09d002e02f7b4c902a7394eec7712e0f855c0408cfdf38711a24"],[["0x1ae35c8c2c5edde29cb66d5ceafc718cbb5614ec775938c3fc6e06f965098ffe", "0x024baf74f2a1342ed11ebc37c4e37f4918af857bdb2f27300da4eeb60a5c56cc"],["0x0e2dba81f8ce98a1420725c1e099f31fb3499ec4edca188214713e42a538130d", "0x2dfe5c493ed18a8d3a540efe906c07cf2a4d39494e5f9300e203561b164ae85b"]],["0x0e07502513914d5aeda7d794e3237927a548f31e79067a3f2d2d3a3fa76930df", "0x1f7984411440e8f3031cfeee751590cbb28924b7b59b4b3857c9bf4724e12d91"],["0x0db7730bdd90c823601ed32395c8b2f3307fd4adc477ca22bf3ed406c1b3ae4a","0x00000000000000000000006d6f632e7061656863656d616e4074726f70707573","0x00000000000000000000000000000000000000000000343230322f32302f3730","0x00000000000 …
```

Upload keys and run scripts

---

client/src/components/Deposit/revolut/NewPosition.tsx
client/src/components/Deposit/venmo/NewPosition.tsx
client/src/components/ProofGen/MailTable.tsx
client/src/components/Registration/garanti/ExistingRegistration.tsx
client/src/components/Registration/hdfc/ExistingRegistration.tsx
client/src/components/Registration/revolut/ExistingRegistration.tsx
client/src/components/Registration/venmo/ExistingRegistration.tsx
client/src/components/Swap/SwapModal.tsx
client/src/components/Swap/garanti/OnRamp.tsx
client/src/components/Swap/hdfc/OnRamp.tsx
client/src/components/Swap/revolut/OnRamp.tsx
client/src/components/Swap/venmo/OnRamp.tsx
client/src/components/layouts/EnvironmentBanner.tsx
client/src/components/layouts/MenuDropdown/index.tsx
client/src/helpers/cards.ts
client/src/helpers/docUrls.ts

Fix docs url

---

circuits-circom/circuits/namecheap/build/namecheap_push/namecheap_push_js/generate_witness.js
circuits-circom/circuits/namecheap/build/namecheap_push/namecheap_push_js/witness_calculator.js
circuits-circom/package/package.json

- Also bump generate inputs package version

Add namecheap build files
